version: "3"
services:
    db:
        image: mysql:latest
        container_name: api_db
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./devdb:/var/lib/mysql
            - ./mysql_schema:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

