-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 00:53:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kuitti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kuitti` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kuitti` (
  `idKuitti` INT NOT NULL AUTO_INCREMENT,
  `idTuote` INT NULL,
  PRIMARY KEY (`idKuitti`),
  INDEX `idTuote_idx` (`idTuote` ASC) VISIBLE,
  CONSTRAINT `tuotteet`
    FOREIGN KEY (`idTuote`)
    REFERENCES `mydb`.`Tuote` (`idTuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ravintola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ravintola` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ravintola` (
  `idRavintola` INT NOT NULL AUTO_INCREMENT,
  `menu` INT NULL,
  `tilaukset` INT NULL,
  `Nimi` VARCHAR(120) NOT NULL,
  `Osoite` VARCHAR(100) NOT NULL,
  `Paikkakunta` VARCHAR(120) NOT NULL,
  `saldo` DECIMAL NULL,
  `kuva` VARCHAR(255) NULL,
  `kuvaus` VARCHAR(255) NULL,
  `aukioloaika` DATE NULL,
  `hitataso` ENUM('€', '€€', '€€€', '€€€€') NULL,
  `tyyppi` ENUM('b', 'ff', 'fc', 'cd', 'fd') NULL,
  `Ravintolacol` VARCHAR(45) NULL,
  `salasana` VARCHAR(256) NULL,
  `Ravintolacol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idRavintola`),
  INDEX `idTuote_idx` (`menu` ASC) VISIBLE,
  INDEX `idKuitti_idx` (`tilaukset` ASC) VISIBLE,
  CONSTRAINT `menu tuotteet`
    FOREIGN KEY (`menu`)
    REFERENCES `mydb`.`Tuote` (`idTuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tilatut tuotteet`
    FOREIGN KEY (`tilaukset`)
    REFERENCES `mydb`.`Tilaus` (`idTilaus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tilaus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tilaus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tilaus` (
  `idTilaus` INT NOT NULL AUTO_INCREMENT,
  `Toimitusaika` DATE NULL,
  `Hinta` DECIMAL NOT NULL,
  `idKuitti` INT NULL,
  `tila` ENUM('valmistumassa', 'toimituksessa', 'toimitettu', 'vastaanotettu') NULL,
  PRIMARY KEY (`idTilaus`),
  INDEX `idKuitti_idx` (`idKuitti` ASC) VISIBLE,
  CONSTRAINT `tilauksen kuitti`
    FOREIGN KEY (`idKuitti`)
    REFERENCES `mydb`.`Kuitti` (`idKuitti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tuote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tuote` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tuote` (
  `idTuote` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(100) NOT NULL,
  `kuvaus` VARCHAR(255) NULL,
  `kategoria` ENUM('p', 'j', 'a') NOT NULL,
  `hinta` DECIMAL NOT NULL,
  `kuva` VARCHAR(255) NULL,
  PRIMARY KEY (`idTuote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kayttaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kayttaja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kayttaja` (
  `idKayttaja` INT NOT NULL AUTO_INCREMENT,
  `Etunimi` VARCHAR(45) NOT NULL,
  `Sukunimi` VARCHAR(45) NOT NULL,
  `Osoite` VARCHAR(100) NOT NULL,
  `Paikkakunta` VARCHAR(120) NOT NULL,
  `Puhelinnnumero` VARCHAR(13) NOT NULL,
  `Ika` INT(120) NOT NULL,
  `tilaus` INT NULL,
  `historia` INT NULL,
  `saldo` DECIMAL NULL,
  `kayttajatunus` VARCHAR(255) NULL,
  `salasana` VARCHAR(256) NULL,
  `kayttajacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKayttaja`),
  UNIQUE INDEX `kayttajaId_UNIQUE` (`idKayttaja` ASC) VISIBLE,
  INDEX `idTilaus_idx` (`tilaus` ASC) VISIBLE,
  INDEX `idKuitti_idx` (`historia` ASC) VISIBLE,
  UNIQUE INDEX `kayttajatunus_UNIQUE` (`kayttajatunus` ASC) VISIBLE,
  UNIQUE INDEX `salasana_UNIQUE` (`salasana` ASC) VISIBLE,
  CONSTRAINT `tilaukset`
    FOREIGN KEY (`tilaus`)
    REFERENCES `mydb`.`Tilaus` (`idTilaus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kuitit`
    FOREIGN KEY (`historia`)
    REFERENCES `mydb`.`Kuitti` (`idKuitti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
