-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 00:53:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kuitti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kuitti` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kuitti` (
  `idKuitti` INT NOT NULL AUTO_INCREMENT,
  `idTuote` INT NULL,
  PRIMARY KEY (`idKuitti`),
  INDEX `idTuote_idx` (`idTuote` ASC) VISIBLE,
  CONSTRAINT `Tuotteet`
    FOREIGN KEY (`idTuote`)
    REFERENCES `mydb`.`Tuote` (`idTuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ravintola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ravintola` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ravintola` (
  `idRavintola` INT NOT NULL AUTO_INCREMENT,
  `Omistaja` INT NULL,
  `Menu` INT NULL,
  `Tilaukset` INT NULL,
  `Nimi` VARCHAR(120) NOT NULL,
  `Osoite` VARCHAR(100) NOT NULL,
  `Paikkakunta` VARCHAR(120) NOT NULL,
  `Saldo` DECIMAL NULL,
  `Kuva` VARCHAR(255) NULL,
  `Kuvaus` VARCHAR(255) NULL,
  `Aukioloaika` VARCHAR(255) NULL,
  `Hintataso` ENUM('e', 'ee', 'eee', 'eeee') NULL,
  `Tyyppi` ENUM('b', 'ff', 'fc', 'cd', 'fd') NULL,
  PRIMARY KEY (`idRavintola`),
  INDEX `idTuote_idx` (`Menu` ASC) VISIBLE,
  INDEX `idKuitti_idx` (`Tilaukset` ASC) VISIBLE,
  INDEX `idKayttaja_idx` (`Omistaja` ASC) VISIBLE,
  CONSTRAINT `Menu Tuotteet`
    FOREIGN KEY (`Menu`)
    REFERENCES `mydb`.`Tuote` (`idTuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tilatut Tuotteet`
    FOREIGN KEY (`Tilaukset`)
    REFERENCES `mydb`.`Tilaus` (`idTilaus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Omistajat`
    FOREIGN KEY idKayttaja_idx (`Omistaja`)
    REFERENCES `mydb`.`Kayttaja` (`idKayttaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tilaus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tilaus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tilaus` (
  `idTilaus` INT NOT NULL AUTO_INCREMENT,
  `Toimitusaika` VARCHAR(255) NULL,
  `Hinta` DECIMAL NOT NULL,
  `idKuitti` INT NULL,
  `Tila` ENUM('valmistumassa', 'toimituksessa', 'toimitettu', 'vastaanotettu') NULL,
  PRIMARY KEY (`idTilaus`),
  INDEX `idKuitti_idx` (`idKuitti` ASC) VISIBLE,
  CONSTRAINT `tilauksen kuitti`
    FOREIGN KEY (`idKuitti`)
    REFERENCES `mydb`.`Kuitti` (`idKuitti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tuote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tuote` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tuote` (
  `idTuote` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(100) NOT NULL,
  `Kuvaus` VARCHAR(255) NULL,
  `Kategoria` ENUM('p', 'j', 'a') NOT NULL,
  `Hinta` DECIMAL NOT NULL,
  `Kuva` VARCHAR(255) NULL,
  `Valmistaja` INT NOT NULL,
  PRIMARY KEY (`idTuote`),
  CONSTRAINT `Tuotteen valmistaja`
    FOREIGN KEY (`Valmistaja`)
    REFERENCES `mydb`.`Ravintola` (`idRavintola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kayttaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kayttaja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kayttaja` (
  `idKayttaja` INT NOT NULL AUTO_INCREMENT,
  `Etunimi` VARCHAR(45) NOT NULL,
  `Sukunimi` VARCHAR(45) NOT NULL,
  `Osoite` VARCHAR(100) NOT NULL,
  `Paikkakunta` VARCHAR(120) NOT NULL,
  `Puhelinnumero` VARCHAR(13) NOT NULL,
  `Ika` INT(120) NOT NULL,
  `Tilaus` INT NULL,
  `Historia` INT NULL,
  `Saldo` DECIMAL NULL,
  `Kayttajatunnus` VARCHAR(255) NULL,
  `Salasana` VARCHAR(256) NULL,
  `Rooli` ENUM('Omistaja', 'Asiakas') NOT NULL,
  PRIMARY KEY (`idKayttaja`),
  UNIQUE INDEX `idKayttaja_UNIQUE` (`idKayttaja` ASC) VISIBLE,
  INDEX `idTilaus_idx` (`Tilaus` ASC) VISIBLE,
  INDEX `idKuitti_idx` (`Historia` ASC) VISIBLE,
  UNIQUE INDEX `kayttajatunus_UNIQUE` (`kayttajatunnus` ASC) VISIBLE,
  UNIQUE INDEX `salasana_UNIQUE` (`Salasana` ASC) VISIBLE,
  CONSTRAINT `Tilaukset`
    FOREIGN KEY (`Tilaus`)
    REFERENCES `mydb`.`Tilaus` (`idTilaus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Kuitit`
    FOREIGN KEY (`Historia`)
    REFERENCES `mydb`.`Kuitti` (`idKuitti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP USER IF EXISTS 'user_nimi'@'%';

CREATE USER 'user_nimi'@'%' IDENTIFIED BY 'user_passwd';
GRANT ALL PRIVILEGES ON mydb.* TO 'user_nimi'@'%';
FLUSH PRIVILEGES;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
